const ITEM_MAXIMUM_QUALITY = 50;
const ITEM_MINIMUM_QUALITY = 0;
const SULFURAS_QUALITY = 80;
const BP_DOUBLE_RATE_DATE = 10;
const BP_TRIPLE_RATE_DATE = 5;

export {ITEM_MAXIMUM_QUALITY, SULFURAS_QUALITY, BP_DOUBLE_RATE_DATE, BP_TRIPLE_RATE_DATE, ITEM_MINIMUM_QUALITY};
